name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Azure Container Registry 
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_URL }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            stackql/oss-activity-monitor:latest
            stackql/oss-activity-monitor:${{ github.sha }}
            ${{ secrets.ACR_REGISTRY_URL }}/oss-activity-monitor:latest
            ${{ secrets.ACR_REGISTRY_URL }}/oss-activity-monitor:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: |
          echo "Docker Image Digest: ${{ steps.buildx.outputs.digest }}"
