name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.REPO_DOCKERHUB_USERNAME }}
          password: ${{ secrets.REPO_DOCKERHUB_TOKEN }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY_URL }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            stackql/oss-activity-monitor:latest
            stackql/oss-activity-monitor:${{ github.sha }}
            ${{ secrets.ACR_REGISTRY_URL }}/oss-activity-monitor:latest
            ${{ secrets.ACR_REGISTRY_URL }}/oss-activity-monitor:${{ github.sha }}

      - name: Image digest
        run: |
          echo "Docker Image Digest: ${{ steps.buildx.outputs.digest }}"
