name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Cache Docker layers
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          push: true
          # file: ./Dockerfile
          # push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            stackql/oss-activity-monitor:latest
            stackql/oss-activity-monitor:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # - name: Login to Azure Container Registry
      #   uses: docker/login-action@v3.1.0
      #   with:
      #     registry: ${{ secrets.ACR_REGISTRY_URL }}
      #     username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      #     password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      # - name: Build and push Docker image to Azure Container Registry
      #   uses: docker/build-push-action@v5.3.0
      #   with:
      #     context: .
      #     # file: ./Dockerfile
      #     # push: ${{ github.ref == 'refs/heads/main' }}
      #     push: true
      #     tags: |
      #       ${{ secrets.ACR_REGISTRY_URL }}/oss-activity-monitor:latest
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: |
          echo "Docker Image Digest: ${{ steps.docker_build.outputs.digest }}"
